config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => '/cable'
  get '/show_additionally', to: 'rooms#show_additionally'
  get '/show_follower', to: 'users#show_follower'

  root 'users#index'
  resources :users, only: %i[index show create destroy edit update] do
    resources :favs, only: %i[create destroy]
    collection do
      get 'search'
    end
    member do
      get 'following', 'followers'
    end
  end
  resources :messages, only: [:create]
  resources :rooms, only: %i[create show index]
  resources :relationships, only: %i[create destroy]
  resources :favs, only: %i[create destroy]
  resources :artists, only: %i[index show search new create] do
    resources :favs, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :comments, only: %i[index show create destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  has_many :favs, dependent: :destroy
  has_many :favorited_users, through: :favs, source: :user
  has_many :users, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :id,    uniqueness: { case_sensitive: false }
  validates :name,  presence: true, uniqueness: { case_sensitive: false }
  validates :icon,  presence: true

  # mount_uploader :icon, ImageUploader

  def already_faved?(artist)
    favs.exists?(artist_id: artist.id)
  end

  def correct_artist
    @artist = Artist.find(params[:id])
    redirect_to(root_url) unless current_artist?(@artist)
  end
end

app/controllers/artists_controller.rb
# frozen_string_literal: true

class ArtistsController < ApplicationController
  # before_create :set_id
  require 'rspotify'
  require 'open-uri'
  RSpotify.authenticate(ENV['CLIENT_KEY'], ENV['CLIENT_SECRET_KEY'])

  def new
    @artist = Artist.new
    @searchartists = RSpotify::Artist.search(params[:search]) if params[:search].present?
  end

  def create
    @artist = Artist.create(artist_params)
    if @artist.save
      flash[:success] = '登録しました'
      redirect_to @artist
    else
      flash[:danger] = '登録できませんでした'
      redirect_to root_path
    end
  end

  def index
    @artist = Artist.all
    @users  = User.all
    @searchartists = RSpotify::Artist.search(params[:search]) if params[:search].present?
  end

  def show
    @artist = Artist.find(params[:id])
    @user_Favorited = @artist.favorited_users
    @comments = @artist.comments.last(10)
    @comment  = current_user.comments.build
   
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.update(artist_params) if @artist_id == current_artist.id
    render action: :edit unless @artist.save
  end

  private

  def artist_params
    params.require(:artist).permit(:id, :icon, :name)
  end
end

app/helpers/artists_helper.rb
# frozen_string_literal: true

module ArtistsHelper
end

app/views/artists/_create_artist.html.erb
<h3>アーティスト名で検索</h3>
  <%= form_with model: @artist, url: artists_path, method: :get, local: true do |form| %>
    <%= form.text_field :search %>
    <%= form.submit 'アーティスト名検索', name: nil %>
  <% end %>
<h1>検索結果</h1>
<div>
<% if @searchartists.present? %>
  <% @searchartists.each do |searchartist| %>
    <div>
      <h3><%= searchartist.name %></h3>
      <h3><%= searchartist.id %></h3>
      <% if searchartist.images.any?%>
        <%image = searchartist.images[2]%>
        <%= image_tag(image["url"])%>
      <%else%>
        <%= image_tag("default.jpg")%>
      <%end%>
    </div>
  <%end%>
<%end%>

app/views/artists/_list.html.erb
<h1>検索結果</h1>
<div>
  <% if @searchartists.present? %>
    <% @searchartists.each do |searchartist| %>
      <div>
        <h3><%= searchartist.name %></h3>
        <p><%= artist_name = searchartist.id %></p>
        <p><%= artist_name %></p>
          <% if searchartist.images.any?%>
            <%image = searchartist.images[1]%>
            <%= image_tag(image["url"])%>
          <%else%>
            <%= image_tag("default.jpg")%>
          <%end%>
      </div>
    <%end%>
  <%end%>

app/views/artists/_new_artist.html.erb
<%= form_with(model: @artist, local: true) do |f| %>
  <%= f.hidden_field :id, value: searchartist.id %>
  <%= f.hidden_field :name, value: searchartist.name %>
    <% if searchartist.images.present?%>
      <% image_url = open(searchartist.images[2]["url"]) %>
      <%= f.hidden_field :icon, value: searchartist.images[2]["url"] %>
    <%end%>
  <%= f.submit "Create new artist", class: "ui primary button" %>
<% end %>

app/views/artists/index.html.erb
<% provide(:title, "Artist") %>

<br>
<%= link_to new_artist_path, class: "ui basic button" do %>
  <i class="headphones icon"></i>アーティストを追加する
<% end %>

<hr>
<% @artist.each do |a| %>
  <a href="/artists/<%= a.id %>">
    <h2 class="ui header">
        <% if a.icon.nil?%>
          <%= image_tag 'default.jpg', class: 'ui circular image'  %>
        <%else%>
          <%= image_tag (a.icon), class: 'ui circular image' %>
        <%end%>
        <%= a.name %>
    </h2>
  </a>
<hr>
<% end %>

app/views/artists/new.html.erb
<% provide(:title, 'New Artist') %>

<h3>アーティスト名で検索 </h3>
  <%= form_with url: new_artist_path, method: :get, local: true do |form| %>
    <div class="ui action input">
    <%= form.text_field :search, class: "ui input focus", placeholder: "Search..." %>
      <%= button_tag '<i class="search icon"></i>'.html_safe, :type => "submit", :class =>"ui button" %>
    </div>
  <% end %>

<% if @searchartists.nil? %>
<% else %>
  <h3>検索結果</h3>
  <div class="ui container">
    <div class="ui six doubling cards">
      <% @searchartists.each do |searchartist| %>
        <div class="ui card">
          <div class="ui image">
            <% if searchartist.images.any? %>
              <%= image_tag(searchartist.images[2]["url"]) %>
              <% image_url = open(searchartist.images[2]["url"]) %>
            <%else%>
              <%= image_tag("default.jpg") %>
            <%end%>
          </div>
          <div class="content">
            <div class="ui tiny header">
              <%= searchartist.name %>
            </div>
          </div>
          <div class="extra content">
            <%= form_with(model: @artist, local: true) do |f| %>
              <%= f.hidden_field :id, value: searchartist.id %>
              <%= f.hidden_field :name, value: searchartist.name %>
                <% if searchartist.images.present?%>
                  <% image_url = open(searchartist.images[2]["url"]) %>
                  <%= f.hidden_field :icon, value: searchartist.images[2]["url"] %>
                <%end%>
              <%= button_tag 'Create!'.html_safe, :type => "submit",:class =>"blue ui button" %>
            <% end %>
          </div>

        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/artists/show.html.erb
<% provide(:title, "Artist") %>

<div class="ui two column grid">
  <div class="column">
    <div class="ui raised segment">
      <div class="item">
        <div class=" ui header"><%= @artist.name %></div>
        <div class="ui small image">
          <% if @artist.icon.nil?%>
            <%= image_tag("default.jpg")%>
          <%else%>
            <%= image_tag (@artist.icon)%>
          <%end%>
        </div>
        <div class="middle aligned content">

          <div class="description">
          </div>
          <div class="extra">
            <%= render 'favs/fav_button' %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if current_user.already_faved?(@artist) %>
    <div class="column">
      <div class="ui raised segment">
        <div class="item">
          <div class="middle aligned content">
            <%= render 'comments/comment_form' %>
            <% if @artist.comments.any? %>      
              <ul class="comments">
                <%= render @comments %>
              </ul>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

</div>

<% if current_user.already_faved?(@artist) %>
  <div class="ui column grid">
    <div class="column">
      <div class="ui raised segment">
        <% if user_signed_in? %>
          <h5>お気にしているユーザー [<%= @user_Favorited.count %>]</h5>
          <div class="ui comments">
            <% @user_Favorited.each do |user| %>
              <div class="comment">
                <a class="ui green image label" href="/users/<%= user.id %>">
                  <% if user.image_url.nil?%>
                    <%= image_tag("default.jpg")%>
                    <%= user.name %>
                  <% else %>
                    <%= image_tag(user.image_url)%>
                    <%= user.name %>
                  <% end %>
                </a>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
<% end %>