config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => '/cable'
  get '/show_additionally', to: 'rooms#show_additionally'
  get '/show_follower', to: 'users#show_follower'

  root 'users#index'
  resources :users, only: %i[index show create destroy edit update] do
    resources :favs, only: %i[create destroy]
    collection do
      get 'search'
    end
    member do
      get 'following', 'followers'
    end
  end
  resources :messages, only: [:create]
  resources :rooms, only: %i[create show index]
  resources :relationships, only: %i[create destroy]
  resources :favs, only: %i[create destroy]
  resources :artists, only: %i[index show search new create] do
    resources :favs, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
  end
  resources :comments, only: %i[index show create destroy]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alert.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a>Copyright(c) 2020 Fes APP! Co.,Ltd</a>
    <a href="https://developer.spotify.com/documentation/web-api/">Supported by Spotify API</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="ui fixed menu">
 
    <div class="left menu">
      <div id="js-sidebar" class="item">
        <i class="icon large grey content"></i>
      </div>
      <%= link_to "Fes app", users_path, id: "logo" %>
    </div>
 
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="ui left demo vertical inverted sidebar labeled icon menu">

  <a class="item" href="/users/<%= current_user.id %>"><%= current_user.name %>さん
  </a>

  <% if current_user.image? %>
    <a class="item" href="/users/<%= current_user.id %>">
      <div class="ui circular mini image">
        <%= image_tag current_user.image_url,alt: "user_image" do %>
          <a href="/users/<%= current_user.id %>"></a>
        <% end %>
      </div>
    </a>
  <% else %>
    <a class="item" href="/users/<%= current_user.id %>">
      <i class="ui circular user icon"></i>
    </a>
  <% end %>

  <%= link_to root_path,class: 'item' do %>
    <i class="ui circular home icon"></i>
  <% end %>

  <%= link_to artists_path,class: 'item' do %>
    <i class="circular headphones icon"></i>
  <% end %>

  <%= link_to destroy_user_session_path,class: 'item', :method => :delete do %>
    <i class="circular sign out alternate icon"></i>
  <% end %>

  <%= link_to edit_user_registration_path,class: 'item' do %>
    <i class="circular cogs icon"></i>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-with, initial-scale=1.0, minimum-scale=1.0">
    <title><%= yield(:title) %> | Fes App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <%= render 'layouts/shim' %>
  </head>

  <body>
      <%= render 'layouts/alert' %>
      
      <div class="pusher">
      <% unless user_signed_in? %>
        <%= render 'layouts/header' %>
        <%= yield %>
      <% else %> 
          <%= render 'layouts/sidebar' %>
          <div class="ui container">
            <%= render 'layouts/header' %>
            <%= yield %>
          </div>
      <% end %>

        <%= render 'layouts/footer' unless @skip_footer %>
        <%= debug(params) if Rails.env.development?  unless @skip_footer%>
    
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.6/semantic.min.js" integrity="sha256-HcON65l89nxNl7vaRECVPe/zNDBzhCcJYBE7O+EcruU=" crossorigin="anonymous"></script>
    <script>
      $('#js-sidebar').click(function() {
        $('.ui.sidebar').sidebar('toggle');
      });
    </script>
  </body>
</html>